name: CI/CD Build Android APK

on:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential ccache git zlib1g-dev openjdk-17-jdk
        pip install --upgrade pip
        pip install cython==0.29.36 buildozer

    - name: Build with Buildozer
      env:
        ANDROID_NDK_HOME: /usr/local/lib/android/sdk/ndk/25.2.9519653
        ANDROIDNDK: /usr/local/lib/android/sdk/ndk/25.2.9519653
      run: |
        yes | buildozer -v android debug
      run: |
        yes | buildozer -v android debug

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v3
      with:
        name: package
        path: bin/*.apk
